# Autogenerated by nbdev

d = { 'settings': { 'branch': 'gh-pages',
                'doc_baseurl': '/nbdev-hello',
                'doc_host': 'https://yveshema.github.io',
                'git_url': 'https://github.com/yveshema/nbdev-hello',
                'lib_path': 'nbdev_hello'},
  'syms': {'nbdev_hello.hello': {'nbdev_hello.hello.say_hello': ('hello.html#say_hello', 'nbdev_hello/hello.py')}}}
